FROM openjdk:17-jdk
WORKDIR Passenger/Dir/passenger
COPY target/Passenger-Reservation-0.0.1-SNAPSHOT.jar /Passenger/Dir/passenger/Reservation-Passenger-Service.jar
CMD ["java","-jar","Reservation-Passenger-Service.jar"]