FROM openjdk:21-jdk-slim
WORKDIR Configworking/Dir/Con
COPY target/Config-Server-0.0.1-SNAPSHOT.jar /Configworking/Dir/Con/Reservation-Config-Server.jar
CMD ["java","-jar","Reservation-Config-Server.jar"]