spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: User
              uri: lb://User-Service
              predicates:
                - Path=/user/**
            - id: Payment
              uri: lb://Payment-Service
              predicates:
                - Path=/payment/**
            - id: Booking
              uri: lb://Booking-Service
              predicates:
                - Path=/booking/**
            - id: Train
              uri: lb://Train-Service
              predicates:
                - Path=/rail/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
management:
  endpoints:
    web:
      exposure:
        include:
          - health