FROM openjdk:21-jdk-slim
WORKDIR Bookingworking/Dir/booking
COPY target/Booking-Service-0.0.1-SNAPSHOT.jar /Bookingworking/Dir/booking/Reservation-Booking-Service.jar
CMD ["java","-jar","Reservation-Booking-Service.jar"]