apiVersion: v1
kind: Service
metadata:
  name: reservation-api-service
spec:
  selector:
    app.kubernetes.io/name: reservation-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30011
  type: NodePort