apiVersion: v1
kind: Service
metadata:
  name: reservation-booking-service
spec:
  selector:
    app.kubernetes.io/name: Booking-deployment.yml
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
