apiVersion: v1
kind: Service
metadata:
  name: reservation-config-service
spec:
  selector:
    app.kubernetes.io/name: reservation-config
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8000
