apiVersion: v1
kind: Service
metadata:
  name: reservation-eureka-service
spec:
  selector:
    app.kubernetes.io/name: reservation-eureka
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8761