apiVersion: v1
kind: Service
metadata:
  name: reservation-mysql-service
spec:
  selector:
    app: reservation-mysql-deploy
  ports:
    - protocol: TCP
      port: 3305
      targetPort: 3306
  type: ClusterIP


