apiVersion: v1
kind: Service
metadata:
  name: reservation-payment-service
spec:
  selector:
    app.kubernetes.io/name: reservation-payment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
