apiVersion: v1
kind: Secret
metadata:
  name: secret-basic
type: Opaque
stringData:
  username: user1 # required field for kubernetes.io/basic-auth
  password: pass123 # required field for kubernetes.io/basic-auth
  rootpassword: pass123