apiVersion: v1
kind: Service
metadata:
  name: reservation-train-service
spec:
  selector:
    app.kubernetes.io/name: reservation-train
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081