apiVersion: v1
kind: Service
metadata:
  name: reservation-user-service
spec:
  selector:
    app.kubernetes.io/name: reservation-user
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084